### ISSUE TITLE
Migrate the project to run with VITE environment

### ISSUE THREAD

**Issue by sEver** [qudlaty/BloodAndBullets#159]
Seeing as the Create React App is dead and outdated, we need modern tooling for the project.

**Comment by sEver** [comment]
Seems we have succeeded in the migration, including storybook and a build system working in a way similar to the previous ones and therefore compatible with old method of deployment and publishing.

**Comment by sEver** [comment]
Since we now have eslint rules as they were set by default in Vite, this might cause some linting issues, to be fixed in due time.

**Comment by sEver** [comment]
Linting issues were fixed.

**Comment by qudlaty** [comment]
Great job! 👍
